# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e50a51aca555229762ab901194aa9b94f042af6ccbf979fdc906d3112f7b8c032fbab08fc7b80f0cfe36e47ec1995c9819263684ceef98cf238c3827e61e2a7
  github_client_id: 'd4ad6ff454d17f271032'
  github_client_secret: '9adef5ebf3e230a20d317a704b6b80ed22a77de9'
  google_client_id: '299065232305-qgeq5d1ahbm6ueiddcq3lardjpe7p5f2.apps.googleusercontent.com'
  google_client_secret: 'YMUtrCBoa3YBFWHF0bxCDvol'
  gmail_email: 'puborbar.dev@gmail.com'
  gmail_password: '1ul6uk7j3uonipb9'
  #w3gram_url: https://locky-w3gram.herokuapp.com/
  w3gram_url: http://pwnie.local:3100/
  w3gram_app: vjcsumcbY3aLQZDf
  w3gram_secret: sCjAgtOpD4R8kjdkO0u6s271uKi7We27MTC1Cs9djqM

test:
  secret_key_base: dc29eb2ac35b853681bf7b9da3f6d562ea3d8ce883b4dd45eb39d0de03e1fbe06806bfaf0afb59452d45b8f4f806e9f065f6a3a5fa6a075684686633292ae417
  github_client_id: 'd4ad6ff454d17f271032'
  github_client_secret: '9adef5ebf3e230a20d317a704b6b80ed22a77de9'
  google_client_id: '299065232305-qgeq5d1ahbm6ueiddcq3lardjpe7p5f2.apps.googleusercontent.com'
  google_client_secret: 'YMUtrCBoa3YBFWHF0bxCDvol'
  gmail_email: 'puborbar.dev@gmail.com'
  gmail_password: '1ul6uk7j3uonipb9'
  #w3gram_url: https://locky-w3gram.herokuapp.com/
  w3gram_url: http://pwnie.local:3100/
  w3gram_app: vjcsumcbY3aLQZDf
  w3gram_secret: sCjAgtOpD4R8kjdkO0u6s271uKi7We27MTC1Cs9djqM

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  github_client_id: 'b39ddd38d0e4d644e44b'
  github_client_secret: <%= ENV["GITHUB_SECRET"].inspect %>
  google_client_id: '178010019549-3iivafg4pt44l5rfdnf7q152dk4mn0q0.apps.googleusercontent.com'
  google_client_secret: <%= ENV["GOOGLE_SECRET"].inspect %>
  gmail_email: 'smartcupapp@gmail.com'
  gmail_password: <%= ENV["GMAIL_SECRET"].inspect %>
  w3gram_url: https://locky-w3gram.herokuapp.com/
  w3gram_app: g3I3tgthYmaLyhXb
  w3gram_secret: <%= ENV["W3GRAM_SECRET"].inspect %>
